language: python
os:
- linux
- osx
script: ./build.sh
deploy:
  provider: releases
  api_key:
    secure: LjiJeUZ2WPaOHlX4wFBWDXgUZ8AyPHSW+njoAkGxWN+t5A0JknlRY+epYk5IccU9H4UPHynw3+P1EMgKldpDJSH2V5yvwm0I4rS3fbEPnRrXX8pLzUk9DshN9VfSK29UtwX3wgRKsG6ER0ZnSNL3jY+qPZkUy2/JqTU8bKQse/eQ8M3ZzACtMCFuOir1OF0QDT3wjEx43NOC47hUZbphVwKppoMiBaEdyOnBIQSr3KOi8zmTDRhQHIkJgsjEm+j1TguZ+Pm9FLl7VjQESa+DALVM/vv1oqK2+xUSVt6dkwEh8QVZo9AEzq4xmXtbJpCd08ydqgbW1COQwgkVPtK46oxP2EZ0W1DGq3him8m39Xc19kPG3ywPoR6xiCZdUzSQimxPLQorb0JeOLRD6blXUU8Nj7q6zl/LQJxdnKrQIn15zZiYjXOCt7DOqIlOifxQhP7pfCE3eI0GNzozJz3u5vEiiW/nlh454uRSJMOYY1Tc49DJG3r5NKbMzbbvJBvJF0uHLXZqEcjQ7OlqNhEN9ySTF/rkVIYrvtuylvH31d7HFgSLZ8tUS57UbGzoVZ/3gOTqiTbF69pLRYMIOlDbpcVdry6mUB7kV2DwUSdspNRoUeEljwL5b4zjWUrXfBN0BtGSkcDk96S6A7YgGNNYXQUzPchHRnMgz3M6h+mtV30=
  file: ./bin/nai.tgz
  skip_cleanup: true
  on:
    repo: nicholaschiasson/nai
